### ISSUE TITLE
how to import data from csv file?

### ISSUE THREAD

**Issue by djouamaah** [xuhuasheng/pca#1]

**Comment by xuhuasheng** [comment]
datatpye of input is 2d array in python, you can convert from csv file by referencing other methond.
but it is not impletmented in my code.

**Comment by djouamaah** [comment]
i have csv file i want to analysis the principal component but i have no idea how to do it

**Comment by xuhuasheng** [comment]
Maybe you should write a script first to convert csv to 2d array.
just like that
`import numpy  `
`my_matrix = numpy.loadtxt(open("yourcsv.csv","rb"),delimiter=",",skiprows=0)  `

**Comment by djouamaah** [comment]
can you help me to do that?

**Comment by xuhuasheng** [comment]
I told you try this 
`my_matrix = numpy.loadtxt(open("yourcsv.csv","rb"),delimiter=",",skiprows=0)`
it can convert csv to 2d array.
If it still doesn't work, try to  get help from others.
